import {
  Building2,
  CheckCircle2,
  Users,
  Wrench,
  CreditCard,
  Landmark,
  Receipt,
  Bot,
  RefreshCw,
  Shield,
  BarChart3,
  Plug,
  Cpu,
  Factory,
  Handshake,
  HardHat,
  HeartPulse,
  Lightbulb,
  Megaphone,
  Settings,
  Palette,
  Ruler,
  Scale,
  ShoppingCart,
  ShieldCheck,
  Sprout,
  Stethoscope,
  Store,
  Video,
  Film,
  Car,
  Smile,
} from "lucide-react";

const registry: Record<string, unknown> = {
  wrench: Wrench,
  users: Users,
  building2: Building2,
  checkcircle2: CheckCircle2,
  CheckCircle2: CheckCircle2,
  CreditCard: CreditCard,
  Landmark: Landmark,
  Receipt: Receipt,
  Bot: Bot,
  RefreshCw: RefreshCw,
  Shield: Shield,
  BarChart3: BarChart3,
  Plug: Plug,
  Cpu: Cpu,
  Factory: Factory,
  Handshake: Handshake,
  HardHat: HardHat,
  HeartPulse: HeartPulse,
  Lightbulb: Lightbulb,
  Megaphone: Megaphone,
  Settings: Settings,
  Palette: Palette,
  Ruler: Ruler,
  Scale: Scale,
  ShoppingCart: ShoppingCart,
  ShieldCheck: ShieldCheck,
  Sprout: Sprout,
  Stethoscope: Stethoscope,
  Store: Store,
  Video: Video,
  Film: Film,
  Car: Car,
  Smile: Smile,
};

export function getLucideIcon(iconKey: string | null) {
  if (!iconKey) return null;
  const direct = registry[iconKey];
  if (direct) return direct as typeof Wrench;
  const normalized = registry[iconKey.toLowerCase()];
  return (normalized ?? null) as typeof Wrench | null;
}

